# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  run_tests:
    docker:
      - image: cimg/node:18.7.0
    steps:
      - checkout
      - run:
          name: "Run npm ci"
          command: "npm ci"
      - run:
          name: "Run build"
          command: "npm run build"
      - run:
          name: "Run lints and unit tests"
          command: "npm test"

workflows:
  build:
    jobs:
    - run_tests:
        filters:
          branches:
            only: /.*/
          tags:
            only: /.*/
